### ISSUE TITLE
Issue installing panaroo on Mac M1 with Ventura

### ISSUE THREAD

**Issue by lurialeslie** [gtonkinhill/panaroo#237]
Hi @gtonkinhill 

I have been trying since two weeks to install panaroo on my machine an M1 air with Ventura.
I had issue with both conda and mamba.
Below  and attached are the error messages.

`conda activate panaroo`
`conda install -c conda-forge -c bioconda -c defaults 'panaroo>=1.3'

Error message

`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                         

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions`

`mamba install -c conda-forge -c bioconda -c defaults 'panaroo>=1.3'`
Error message

`Looking for: ["panaroo[version='>=1.3']"]

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/osx-arm64                                           No change

Pinned packages:
  - python 3.9.*

Could not solve for environment specs
The following package could not be installed
└─ panaroo >=1.3  is uninstallable because it requires
   └─ cd-hit  , which does not exist (perhaps a missing channel).`

<img width="1440" alt="Screenshot 2023-06-13 at 13 39 05" src="https://github.com/gtonkinhill/panaroo/assets/61629403/7e03e84e-91c2-454b-b296-9cb7a6a86383">
<img width="1440" alt="Screenshot 2023-06-13 at 13 38 11" src="https://github.com/gtonkinhill/panaroo/assets/61629403/4aca36e4-0664-476f-9e7e-611868ce9af2">

**Comment by lurialeslie** [comment]
The installation of CD-HIT is related to gcc and g+ which is quite complicated.
I will wait for the update.

**Comment by nzmacalasdair** [comment]
An alternative to compiling cd-hit yourself would be to use [macports](https://ports.macports.org/), where cd-hit is [available](https://ports.macports.org/port/cdhit/), if you have macports installed.

Installing cd-hit this way should also allow for manual panaroo installation.

**Comment by lurialeslie** [comment]
Many thanks @nzmacalasdair. I followed the guidance but still received the same error message about cd-hit when installing panaroo.  I have checked that the port was installed as provided in the tuto but still. Any thoughts of why I still have it?

**Comment by nzmacalasdair** [comment]
Glad you managed to get cd-hit installed!

Can I check that you're installing panaroo manually, according to the [guide](https://gtonkinhill.github.io/panaroo/#/gettingstarted/installation?id=manual)? You should skip the steps about installing cd-hit and mafft, and start here:

- Download or clone the repository and install by running

If you've installed cd-hit using macports, you'll have to follow proceed with manual installation, installing it with conda will continue to produce the error because conda will try and re-install cd-hit, where it will find that it doesn't have compiled binaries for M1 Macs (and other ARM-based computers), and throw the error you're seeing.

You will also need to install a multiple sequence alignment tool if you are interested in core genome alignment (or aligned pan-genome gene sequences). The default in panaroo is MAFFT ([macports here](https://ports.macports.org/port/mafft/)), but panaroo also supports Clustal Omega and PRANK. 

You may also need to install python dependencies manually (list available below the manual install instructions), I recommend doing this with `pip`, outside of any conda environment, especially base. You can exit conda with `conda deactivate` when in the base environment. If you have multiple versions of python installed on your computer, the best way to install packages with `pip` is with the `python -m pip` command, where `python` is the version of python you want to run panaroo with.

**Comment by lurialeslie** [comment]
Thanks again @nzmacalasdair. I cloned the panaroo repository and installed dependencies manually. However, mafft does not complete installation and loads forever in one step particular step. I have been trying this over the weekend with a very good connection but no changes. See attached.
Likewise, I am getting an issue with edlib please see attached.

<img width="1440" alt="Screenshot 2023-06-19 at 09 08 17" src="https://github.com/gtonkinhill/panaroo/assets/61629403/c1301e3b-6495-48f0-a76f-fa990506a50b">
<img width="1440" alt="Screenshot 2023-06-19 at 09 17 01" src="https://github.com/gtonkinhill/panaroo/assets/61629403/11cae38d-21ae-4237-af30-b2bcef810ec3">
<img width="1440" alt="Screenshot 2023-06-19 at 09 16 59" src="https://github.com/gtonkinhill/panaroo/assets/61629403/9caab39b-37c8-49ad-adff-c914b2659500">
<img width="1440" alt="Screenshot 2023-06-19 at 09 16 47" src="https://github.com/gtonkinhill/panaroo/assets/61629403/e00cc767-266d-4819-b27c-205b1a795ac3">

**Comment by lurialeslie** [comment]
Hi @nzmacalasdair @gtonkinhill 

That was overly complicated for me and I am scared to break my computer.
I have instead got access to another windows machine and virtualize Linux on it.
Panaroo was successfully installed but I am having some difficulties running the basic steps provided in the tutorial.

I run the following code within the directory containing the gff files.
` panaroo -i *.gff -o results --clean-mode strict --remove-invalid-genes`

Here is the error message I got: 


> 

> pre-processing` gff3 files...
> 
>   0%|                                                                           | 0/3 [00:00<?, ?it/s]Problem reading GFF3 file:  GCF_002895385.1.gff
>   0%|                                                                           | 0/3 [00:00<?, ?it/s]
> Error reading prokka input!
> Traceback (most recent call last):
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 278, in process_prokka_input
>     gene_sequence_list = Parallel(n_jobs=n_cpu)(
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 1855, in __call__
>     return output if self.return_generator else list(output)
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 1784, in _get_sequential_output
>     res = func(*args, **kwargs)
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 127, in get_gene_sequences
>     raise RuntimeError("Error reading prokka input!")
> RuntimeError: Error reading prokka input!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/luria/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
>     sys.exit(main())
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 312, in main
>     process_prokka_input(args.input_files, args.output_dir,
>   File "/home/luria/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 290, in process_prokka_input
>     raise RuntimeError("Error reading prokka input!")
> RuntimeError: Error reading prokka input!


I came across a similar issue addressed by @gtonkinhill and I tried to use the script provided  convert_refseq_to_prokka [https://github.com/gtonkinhill/panaroo/blob/master/panaroo/prokka.py](url) to solve it but still getting an error message below 

> Traceback (most recent call last):
>   File "/home/luria/s.aureus_trial/ncbi_dataset/convert_refseq_to_prokka_gff.py", line 16, in <module>
>     from .biocode_convert import convert_gbk_gff3
> ImportError: attempted relative import with no known parent package

What am I doing wrong?

**Comment by gtonkinhill** [comment]
Hi,

This looks like Panaroo is still not installed properly as you are missing the biocode dependency. If you have an IT person at your institute it might be best to contact them for help to get it running on your system.

**Comment by lurialeslie** [comment]
Hi

It is the IT who installed it in the server.
I just tried to run the command as presented in the quick start.
